"""Enforce the project's separate line- and branch-coverage thresholds.

``coverage.py`` can only fail on one combined number. The project states two targets — 90%
of lines and 85% of branches — so this script reads ``coverage.xml`` and checks them
independently. It runs after ``pytest --cov`` in ``make coverage`` and in CI.

Usage::

    python scripts/check_coverage.py
    python scripts/check_coverage.py --xml coverage.xml --line 90 --branch 85
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from xml.etree import ElementTree

DEFAULT_LINE_THRESHOLD = 90.0
DEFAULT_BRANCH_THRESHOLD = 85.0


def read_rates(path: Path) -> tuple[float, float]:
    """Read line and branch coverage percentages from a Cobertura XML report.

    Args:
        path: Path to ``coverage.xml``.

    Returns:
        A ``(line_percent, branch_percent)`` tuple.

    Raises:
        SystemExit: If the file is missing or unparseable.
    """
    if not path.is_file():
        raise SystemExit(f"coverage report not found: {path}; run pytest --cov first")
    try:
        # `coverage.xml` is generated by coverage.py from our own test run, not fetched
        # from anywhere, so parsing it with the standard library is appropriate.
        root = ElementTree.parse(path).getroot()  # noqa: S314
    except ElementTree.ParseError as error:
        raise SystemExit(f"coverage report {path} is not valid XML: {error}") from error
    return float(root.get("line-rate", 0.0)) * 100.0, float(root.get("branch-rate", 0.0)) * 100.0


def main() -> int:
    """Check the thresholds and report the outcome.

    Returns:
        ``0`` when both thresholds are met, ``1`` otherwise.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml", type=Path, default=Path("coverage.xml"))
    parser.add_argument("--line", type=float, default=DEFAULT_LINE_THRESHOLD)
    parser.add_argument("--branch", type=float, default=DEFAULT_BRANCH_THRESHOLD)
    arguments = parser.parse_args()

    line, branch = read_rates(arguments.xml)
    print(f"line coverage   : {line:.2f}%  (target {arguments.line:.0f}%)")
    print(f"branch coverage : {branch:.2f}%  (target {arguments.branch:.0f}%)")

    failures: list[str] = []
    if line < arguments.line:
        failures.append(f"line coverage {line:.2f}% is below {arguments.line:.0f}%")
    if branch < arguments.branch:
        failures.append(f"branch coverage {branch:.2f}% is below {arguments.branch:.0f}%")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        return 1
    print("coverage gate passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
